### ISSUE TITLE
can't understand wps configuration  after install lizmap web client

### ISSUE THREAD

**Issue by gaowudao** [3liz/lizmap-wps-web-client-module#1]
Dear friend,

I can run lizmap web client, but i don't know how to configure  wps configuration in php.ini. **Can you give a specific example: including wps_url, wps_rootDirectories, redis_port and ows_url.** I am a beginner about how to configure wms, wps service.
  
Thank you very much.

[wps]
wps_url=http://wps:8080
wps_rootDirectories=/projects/wps
redis_host=localhost
redis_port=6379
redis_key_prefix=lzmwps
ows_url=http://map:8080

**Comment by dmarteau** [comment]
The README file gives  all the necessary details for configuring the wps client. Sorry, but I don't know what you expect to be 'more specific'.
Note that you will need to set up a WPS service such as this one: https://github.com/3liz/py-qgis-wps in order to be able to use wps service with Lizmap.
