### ISSUE TITLE
Not working with Lizmap 3.4 or superior

### ISSUE THREAD

**Issue by dmarteau** [3liz/lizmap-wps-web-client-module#12]
The module does not work with Lizmap 3.4 anymore.

The popup "Chargement des données" does not close even when the map is loaded.

Works with Lizmap 3.3.12

How to reproduce:
Run tests:
```
cd tests
make run
```
* Configure the project 'france_parts'
* Open the project Map

Test with Lizmap 3.3.12 

```
make clean
make run LIZMAP_VERSION_TAG=3.3.12
```

**Comment by dmarteau** [comment]
There is Javascript errors:

```
Uncaught (in promise) TypeError: OpenLayers.Format.WPSDescribeProcess is undefined
    uicreated http://localhost:9090/index.php/jelix/www/getfile?targetmodule=wps&file=wps.js:1570
    triggerEvent http://localhost:9090/assets/js/OpenLayers-2.13/OpenLayers.js:255
    init http://localhost:9090/assets/js/map.js:6276
getfile:1570:13
```

```
Uncaught TypeError: OpenLayers.Format.WPSCapabilities is not a constructor
    success http://localhost:9090/index.php/jelix/www/getfile?targetmodule=wps&file=wps.js:20
    runCallbacks http://localhost:9090/assets/js/OpenLayers-2.13/OpenLayers.js:1561
    onreadystatechange http://localhost:9090/assets/js/OpenLayers-2.13/OpenLayers.js:1557
    dispatchEvent http://localhost:9090/assets/js/OpenLayers-2.13/OpenLayers.js:1591
    fReadyStateChange http://localhost:9090/assets/js/OpenLayers-2.13/OpenLayers.js:1594
    onreadystatechange http://localhost:9090/assets/js/OpenLayers-2.13/OpenLayers.js:1577
getfile:20:32
    success http://localhost:9090/index.php/jelix/www/getfile?targetmodule=wps&file=wps.js:20
    runCallbacks http://localhost:9090/assets/js/OpenLayers-2.13/OpenLayers.js:1561
    onreadystatechange http://localhost:9090/assets/js/OpenLayers-2.13/OpenLayers.js:1557
    dispatchEvent http://localhost:9090/assets/js/OpenLayers-2.13/OpenLayers.js:1591
    fReadyStateChange http://localhost:9090/assets/js/OpenLayers-2.13/OpenLayers.js:1594
    onreadystatechange http://localhost:9090/assets/js/OpenLayers-2.13/OpenLayers.js:1577

```

**Comment by nboisteault** [comment]
@ daim I have added the OpenLayers.Format.WPSCapabilities class here :  https://github.com/3liz/lizmap-web-client/commit/f44bf04f554f336b320b70da0a935b7387289260
Can you test with release_3_4 branch please?

**Comment by pcav** [comment]
Is this plugin updated to current 3.4.1 release?
Thanks.

**Comment by rldhont** [comment]
To fix  the bug, we have to include `Format/WPSDescribeProcess/v_1_0_0.js`

**Comment by dmarteau** [comment]
This is still not fixed, and prevent using WPS module with limap 3.4+

**Comment by rldhont** [comment]
@nboisteault Commit https://github.com/3liz/ol2/blob/lizmap-build-2.13.1/build/lizmap.cfg in `3liz/ol2/lizmap-build-2.13.1`

**Comment by nboisteault** [comment]
> To fix the bug, we have to include `Format/WPSDescribeProcess/v_1_0_0.js`

It is `OpenLayers/Format/WPSDescribeProcess.js`

**Comment by dmarteau** [comment]
Does not work: same error

```
 /build.manifest:
name=lizmap-web-client
version=3.4-dev
buildid=202105201541
commitid=c6edf5561
```

**Comment by nboisteault** [comment]
@dmarteau I have made another commit, first was wrong : https://github.com/3liz/lizmap-web-client/commit/a3ee6c2cf79e5d308c3f64d5e54cdfe4070ca92a

**Comment by nboisteault** [comment]
@dmarteau I have : 
```
web_1     | nginx: [alert] could not open error log file: open() "/var/log/nginx/error.log" failed (13: Permission denied)
web_1     | 2021/05/20 14:32:19 [emerg] 1#1: open() "/var/log/nginx/error.log" failed (13: Permission denied)
tests_web_1 exited with code 1

```

**Comment by dmarteau** [comment]
You nee to do `make clean` in order te get rid of all the old configuration which was created as root.

**Comment by nboisteault** [comment]
@dmarteau Ok I can debug now.
@rldhont I see that the WPS module needs many OpenLayers files that are not needed by Lizmap. I'd like to not bloat built OpenLayers.js but let WPS module and modules in general add their OpenLayers dependencies files. Are you ok with that ?

**Comment by nboisteault** [comment]
@dmarteau Ok I can debug now.
@rldhont I see that the WPS module needs many OpenLayers files that are not needed by Lizmap. I'd like to not bloat built OpenLayers.js but let WPS module and modules in general add their OpenLayers dependencies files. Are you ok with that ?

**Comment by rldhont** [comment]
@nboisteault I am ok with that modules add their OpenLayers dependencies files.

**Comment by pcav** [comment]
Confirmed with current version. Pity it's unusable now.

**Comment by pcav** [comment]
Thanks @nboisteault

**Comment by nboisteault** [comment]
@pcav you're welcome. Could you test `master` branch before we make a release please?

**Comment by pcav** [comment]
We can confirm that it works with LWC 3.4. With 3.5 however, WPS capabilities are not loaded.
Thanks again @nboisteault

**Comment by nboisteault** [comment]
Thanks @pcav. Concerning Lizmap 3.5, it has been fixed by https://github.com/3liz/lizmap-web-client/pull/2370 so final 3.5 release will work.

**Comment by Gustry** [comment]
@pcav You can use the latest package from 3.5 available https://packages.3liz.org/pub/lizmap/unstable/3.5/
Take the date from today, it should work.

**Comment by pcav** [comment]
Great, thanks again!

Il 11 luglio 2021 09:45:10 CEST, Nicolas Boisteault ***@***.***> ha scritto:
>Thanks @pcav. Concerning Lizmap 3.5, it has been fixed by
>https://github.com/3liz/lizmap-web-client/pull/2370 so final 3.5
>release will work.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/3liz/lizmap-wps-web-client-module/issues/12#issuecomment-877756638

-- 
Sorry for being short

**Comment by pcav** [comment]
OK, thanks a lot.

Il 11 luglio 2021 10:05:11 CEST, "Étienne Trimaille" ***@***.***> ha scritto:
***@***.*** You can use the latest package from 3.5 available
>https://packages.3liz.org/pub/lizmap/unstable/3.5/
>Take the date from today, it should work.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/3liz/lizmap-wps-web-client-module/issues/12#issuecomment-877758971

-- 
Sorry for being short
