### ISSUE TITLE
Computed layer from WPS are not displayed

### ISSUE THREAD

**Issue by dmarteau** [3liz/lizmap-wps-web-client-module#19]
When running tests processes (Qgis buffer, centroids): computed layers appears in legend but are not displayed.

Qgis 3.16
Lizmap: 3.4.4

**Comment by nboisteault** [comment]
@pcav says it works : https://github.com/3liz/lizmap-wps-web-client-module/issues/12#issuecomment-877686560
Maybe issue occurs only with our test stack.
@drillinP could you test WPS module with a fresh Lizmap instance?

**Comment by chrimohr** [comment]
I've ran into the same issue. As a workaround I'm using the server IP address instead of http://map:8080 in the WPS part of  docker-compose.yml.

**Comment by nboisteault** [comment]
Thanks @chrimohr . @dmarteau any change in `3liz/qgis-wps` that could explain this?

**Comment by dmarteau** [comment]
@nboisteault  I have tested:

* Result project create -> Ok
* All status links from `/status/` api - used by lizmap to get urls to result layer. -> Ok
* WMS link from WPS response -> Ok
* No JS errors in the console.

From wps/ows/ POV all is OK.

What I see is that Lizmap does not send any OWS request te the map service for fetching the result layer (but seems to get the correct status) - This has to be investigated in Lizmap. 

Also there is no logs anywhere (in lizmap or in file) indicating potential errors (Lizmap should log remote requests at least for the sake of debugging).

**Comment by rldhont** [comment]
I have made 1 test:

1. make pull
2. make run
3. Go to 127.0.0.1:9090
4. Click on France parts map in Test repository
5. Run a buffer algorithm on france_parts layer
6. Check the HTML and find that OpenLayers using the host 127.0.0.1:9090:8080
7. Check the WPS GetResult response it contains

```xml
<wps:ExecuteResponse xsi:schemaLocation="http://www.opengis.net/wps/1.0.0 http://schemas.opengis.net/wps/1.0.0/wpsExecute_response.xsd" service="WPS" version="1.0.0" xml:lang="en-US" serviceInstance="http://wps:8080/?service=WPS&request=GetCapabilities" statusLocation="http://wps:8080/ows/?service=WPS&request=GetResults&uuid=02eb3780-e550-11eb-b94e-0242ac120003">
  <wps:Process wps:processVersion="1.0generic">
    <ows:Identifier>pyqgiswps_test:qgisbuffer</ows:Identifier>
    <ows:Title>QGIS Buffer</ows:Title>
  </wps:Process>
  <wps:Status creationTime="2021-07-15T09:35:37Z">
    <wps:ProcessSucceeded>Task finished</wps:ProcessSucceeded>
  </wps:Status>
  <wps:ProcessOutputs>
    <wps:Output>
      <ows:Identifier>OUTPUT</ows:Identifier>
      <ows:Title>Buffered</ows:Title>
      <ows:Abstract>Buffered</ows:Abstract>
      <wps:Reference href="http://127.0.0.1:9090:8080/index.php/wps/ows/?MAP=wps-results:02eb3780-e550-11eb-b94e-0242ac120003/pyqgiswps_test_qgisbuffer.qgs&service=WMS&request=GetCapabilities&layers=tests" mimeType="application/x-ogc-wms"/>
    </wps:Output>
  </wps:ProcessOutputs>
</wps:ExecuteResponse>
```

When I launch `make run`, I have this message:
```
docker-compose rm -f || true
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.map.ports contains an invalid type, it should be a number, or an object
services.web.ports contains an invalid type, it should be a number, or an object
services.wps.ports contains an invalid type, it should be a number, or an object
Creating environment file for docker-compose
```

**Comment by dmarteau** [comment]
No, this is a problem related to a bad docker-compose environment, it has nothing to do with this issue:

A correct configuration give the following result, which is correct from the docker-compose lizmap service. But the issue is still there. 
```
<!-- py-qgis-wps 1.5.4 -->
<wps:ExecuteResponse xsi:schemaLocation="http://www.opengis.net/wps/1.0.0 http://schemas.opengis.net/wps/1.0.0/wpsExecute_response.xsd" service="WPS" version="1.0.0" xml:lang="en-US" serviceInstance="http://wps:8080/?service=WPS&request=GetCapabilities" statusLocation="http://wps:8080/ows/?service=WPS&request=GetResults&uuid=cf14f35e-e551-11eb-b559-0242ac120005">
<wps:Process wps:processVersion="1.0generic">
<ows:Identifier>pyqgiswps_test:qgisbuffer</ows:Identifier>
<ows:Title>QGIS Buffer</ows:Title>
</wps:Process>
<wps:Status creationTime="2021-07-15T09:48:29Z">
<wps:ProcessSucceeded>Task finished</wps:ProcessSucceeded>
</wps:Status>
<wps:ProcessOutputs>
<wps:Output>
<ows:Identifier>OUTPUT</ows:Identifier>
<ows:Title>Buffered</ows:Title>
<ows:Abstract>Buffered</ows:Abstract>
<wps:Reference href="http://map:8080/ows/?MAP=wps-results:cf14f35e-e551-11eb-b559-0242ac120005/pyqgiswps_test_qgisbuffer.qgs&service=WMS&request=GetCapabilities&layers=buffer1" mimeType="application/x-ogc-wms"/>
</wps:Output>
</wps:ProcessOutputs>
</wps:ExecuteResponse>
```

**Comment by rldhont** [comment]
To do not display the map:8080, the host is replaced. So it has to be fixed in the module.

**Comment by dmarteau** [comment]
`map:8080` is the qgis server host as see by all services defined in the docker-compose and it is perfectly valid.

**Comment by rldhont** [comment]
I logged some information about domain like that:
```
jLog::log('domainName: '.jApp::config()->domainName, 'error');
jLog::log('HTTP_HOST: '.$_SERVER['HTTP_HOST'], 'error');
jLog::log('SERVER_NAME: '.$_SERVER['SERVER_NAME'], 'error');
```
And I give this:
```
2021-07-15 16:28:44     172.18.0.1      error   domainName: 127.0.0.1:9090
2021-07-15 16:28:44     172.18.0.1      error   HTTP_HOST: 127.0.0.1:9090
2021-07-15 16:28:44     172.18.0.1      error   SERVER_NAME: 127.0.0.1:9090
```
So the domainName defined in config files is `127.0.0.1:9090` but I found nothing about `domainName` in config files:
* tests/lizmap/var/lizmap-config/mainconfig.ini.php
* tests/lizmap/var/lizmap-config/localconfig.ini.php
* tests/lizmap/var/lizmap-config/liveconfig.ini.php
* tests/lizmap/var/lizmap-config/index/config.ini.php
* tests/lizmap/etc/localconfig.d/wps.ini.php

@dmarteau is the `LIZMAP_PORT` environment variable used to defined domainName ?

**Comment by dmarteau** [comment]
> is the LIZMAP_PORT environment variable used to defined domainName ?

No, this is just the variable name for the docker-compose environment (.env file)

**Comment by rldhont** [comment]
Ok I did not understand how the domainName in config is set. But if it is dynamically set with the port. The solution is to update `tests/lizmap/var/lizmap-config/localconfig.ini.php` by adding `forceHTTPPort=True`.

**Comment by laurentj** [comment]
We found the issue :

1. nginx sets SERVER_NAME with `$http_host`, which it self comes from HTTP headers. So it can contains port (although the [PHP documentation says](https://www.php.net/manual/en/reserved.variables.server.php) that `SERVER_NAME` should contain the server name (so, from what i understand, without port)...
2. during the configuration processing, Jelix sets `domainName` with SERVER_NAME if `domainName` is empty. It doesn't check if there is a port, because it should not have one (IMHO).

On a production server, most of time the server is on standard port (80 or 443) so there is no issue. However, if the web server is on a non-standard port, this is an issue.

So there is two mistake here :
- In nginx, setting SERVER_NAME with `$http_host` may not be relevant in some "architecture", but it can be the case so Jelix should check the content of SERVER_NAME, to remove port when needed.
- probably Jelix should not rely on SERVER_NAME but, on the HTTP_POST variable when it fills an empty domainName configuration parameter. And probably it should not cache the result, because if the configuration of nginx is changing, cache values are not anymore valid. But modules relying only on `domainName` and not `jServer::getDomainName()` (which allow to guess the domain name at runtime) may be break.

Anyway, I should make a change into Jelix to support SERVER_NAME having a port number.

**Comment by laurentj** [comment]
An update of Jelix has been landed into all branches. It fixes the support of port number into SERVER_NAME. Bonus: `forceHTTPPort` and `forceHTTPSPort` are guessed automatically when the port is present into HTTP_HOST or SERVER_NAME.

**Comment by Ratcav** [comment]
This fix will be integrated in the official docker images, or is there a quicker way to test the changes?
