### ISSUE TITLE
Masquage des modèles graphiques selon le projet ou le dossier du projet

### ISSUE THREAD

**Issue by prahout59** [3liz/lizmap-wps-web-client-module#25]
Bonjour.

Nous avons réalisé plusieurs modèles graphiques en nous efforçant de les rendre les plus génériques possible.
Cependant, nous avons des cartes métiers sur lesquelles certains modèles peuvent être utilisables et d'autres cartes pour lesquelles certains modèles doivent être masqués car incohérents avec les couches de la carte.

![image](https://user-images.githubusercontent.com/91070758/166886571-47d3d1c0-5904-4eed-a9e7-ca7587e515ca.png)

La question est donc, peut-on masquer des modèles graphiques dans la liste de choix (en python ou en qgis)  selon la carte qui est affichée ? Si oui, comment ?

Cordialement,

**Comment by nboisteault** [comment]
Bonjour,
Vous pouvez cacher des options de la liste déroulante avec du CSS [0]. Par exemple pour un projet, vous définissez un fichier `map.css` dans lequel vous ajoutez `#processing-input-INPUT > option[value="Test de patrick"]`.

[0] : https://docs.lizmap.com/current/fr/publish/customization/themes.html

**Comment by prahout59** [comment]
Bonjour.
Je vais tester cela et je vous tiens informé.

J'ai une autre question qui est peut-être liée au CSS aussi. Quand j'utilise la sélection, le décompte des parcelles sélectionnées s'affiche bien, dans la table attributaire, les lignes sont bien affichées en jaune (sélectionnées) mais, dans la carte elles ne sont pas mises en jaune. Cela a fonctionné un moment et cela ne fonctionne plus. Je suis passé en Qgis 3.22 et Lizmap 3.5.2.
![image](https://user-images.githubusercontent.com/91070758/168249736-83e42ef1-ec8c-4432-9c86-58af5dc13635.png)

J'ai tenté de repasser en version antérieur de Qgis et de Lizmap sur le serveur mais, pas mieux.
Est-ce un problème de CSS dans lizmap-web-client ou un problème dans le module lizmap sur le Desktop Qgis ?

**Comment by Gustry** [comment]
Merci de garder un ticket par question. La deuxième question étant déjà https://github.com/3liz/lizmap-web-client/issues/2985
Pour l'erreur 504, il faut voir les logs sur le serveur. Il doit y avoir un indice.

**Comment by prahout59** [comment]
Ok, je vais attendre la réponse à l'autre [question](https://github.com/3liz/lizmap-web-client/issues/2985) passée en bug. Merci
