### ISSUE TITLE
Anomalous Behaviour of wps module in LWC 3.7.0

### ISSUE THREAD

**Issue by Antoviscomi** [3liz/lizmap-wps-web-client-module#48]
My warped processes works fine but the wps output was not available in LWC 3.7.0 TOC Legend, so the layers I create (i.e. a buffer) is loaded on the map, but can no longer be deactivated, except by reloading the entire map by browser

by jelix debug console it came out this:

<p style="margin: 0px 0px 0px 18px; font-size: 13.3333px; color: rgb(0, 0, 0); font-family: sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(204, 228, 237); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Code: 8192<br>File: /var/www/wgis/lizmap/lizmap/lizmap-modules/wps/classes/wps.listener.php 136</p>
0 | wpsListener->isAvailable() | /var/www/wgis/lizmap/lizmap/lizmap-modules/wps/classes/wps.listener.php | 72
-- | -- | -- | --
1 | wpsListener->onmapDockable() | /var/www/wgis/lizmap/lizmap/vendor/jelix/jelix/lib/jelix/events/EventListener.php | 40
2 | Jelix\Event\EventListener->performEvent() | /var/www/wgis/lizmap/lizmap/vendor/jelix/jelix/lib/jelix/events/ListenerProvider.php | 102
3 | Jelix\Event\ListenerProvider->Jelix\Event\{closure}() | /var/www/wgis/lizmap/lizmap/vendor/jelix/jelix/lib/jelix/events/EventDispatcher.php | 45
4 | Jelix\Event\EventDispatcher->dispatch() | /var/www/wgis/lizmap/lizmap/vendor/jelix/jelix/lib/jelix/events/jEvent.class.php | 306
5 | jEvent::notify() | /var/www/wgis/lizmap/lizmap/modules/view/controllers/lizMap.classic.php | 591
6 | lizMapCtrl->getProjectDockables() | /var/www/wgis/lizmap/lizmap/modules/view/controllers/lizMap.classic.php | 301
7 | lizMapCtrl->index() | /var/www/wgis/lizmap/lizmap/modules/view/controllers/map.classic.php | 21
8 | mapCtrl->index() | /var/www/wgis/lizmap/lizmap/vendor/jelix/jelix/lib/jelix/core/jCoordinator.class.php | 266
9 | jCoordinator->process() | /var/www/wgis/lizmap/lizmap/www/index.php

``

**Comment by Antoviscomi** [comment]
I attacch three screenshot 

![Schermata del 2023-12-19 13-02-54](https://github.com/3liz/lizmap-wps-web-client-module/assets/12639444/ce661235-5322-46e0-b3ba-0cca6189c1b5)
![Schermata del 2023-12-19 13-02-43](https://github.com/3liz/lizmap-wps-web-client-module/assets/12639444/eeadeab8-4a34-4bd8-88ca-eb1305df7313)
![Schermata del 2023-12-19 13-02-28](https://github.com/3liz/lizmap-wps-web-client-module/assets/12639444/59d54f82-600d-4e81-ae62-556c94ba35d2)

**Comment by rldhont** [comment]
It is a known issue. The way lizmap managed the layer tree has changed in Lizmap Web Client 3.7.

**Comment by Antoviscomi** [comment]
Luckily @rldhont, I thought I had configured something wrong , I hope that future versions can fix this problem

**Comment by Antoviscomi** [comment]
@Gustry I tried it yesterday and with new version of wps 0.5.2 on 3.8.1 it seems to be fixed so I close this issue
