### ISSUE TITLE
Wps output not loading and legend it seems too huge on 3.8rc2 

### ISSUE THREAD

**Issue by Antoviscomi** [3liz/lizmap-wps-web-client-module#53]
the process works fine but the result of processing is not loaded in the map, the legend it seems too huge see the screencast
[Video del 23-07-2024 10:29:19.webm](https://github.com/user-attachments/assets/7a8ad397-5b84-4fe9-95b1-56202e174f43)

**Comment by rldhont** [comment]
@Antoviscomi the legend has been fixed, it was an issue in Lizmap Web Client. The fix will be available in 3.8.0 or 3.8-rc.4
You can test it https://packages.3liz.org/pub/lizmap/unstable/3.8/lizmap-web-client-3.8.0-rc.4.zip

Have you check the result of the prosess outside lizmap ? Getting the temp processing directory build by py-qgis-wps ?

**Comment by Antoviscomi** [comment]
@rldhont yes of course I've checked for the output, that it was created and fully works, as you can see in screenshot

![Schermata del 2024-07-23 13-07-20](https://github.com/user-attachments/assets/2be96bdd-aa6f-4ed2-ba4c-4ed706dd0035)

in ordet to test new version I'll do ASAP ;-)

**Comment by rldhont** [comment]
@Antoviscomi if the project is right in QGIS Desktop, the issue probably comes from QGIS Server. Do you have some errors in the Browser Dev  tools ?

**Comment by Antoviscomi** [comment]
@rldhont in browser dev tool there is the error in screenshot repeated seven times

![Schermata del 2024-07-23 15-16-09](https://github.com/user-attachments/assets/f3191bca-e2a5-4456-b566-de58900a7fff)

**Comment by Antoviscomi** [comment]
@rldhont let me know if you need someother information

**Comment by rldhont** [comment]
@Antoviscomi the error is due to this line https://github.com/3liz/lizmap-wps-web-client-module/blob/master/wps/www/wps.js#L1323 The value `'qgisserver'` is unknown and has to be replaced `'qgis'`

**Comment by Antoviscomi** [comment]
@rldhont So, I close this issue
